import type { NextPage } from 'next'
import Head from 'next/head'
import { useState, useEffect } from 'react'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  const [year, setYear] = useState(0)
  const [month, setMonth] = useState('')
  const [day, setDay] = useState(0)
  const [totalDays, setTotalDays] = useState(0)

  const getDaysInMonth = (year: number, month: number) => {
    return new Date(year, month, 0).getDate();
  }

  const getMonthName = (month: number) => {
    switch (month) {
      case 1:
        return 'January'
      case 2:
        return 'February'
      case 3:
        return 'March'
      case 4:
        return 'April'
      case 5:
        return 'May'
      case 6:
        return 'June'
      case 7:
        return 'July'
      case 8:
        return 'August'
      case 9:
        return 'September'
      case 10:
        return 'October'
      case 11:
        return 'November'
      case 12:
        return 'December'
      default:
        return ''
    }
  }

  useEffect(() => {
    const date = new Date();
    const currentYear = date.getFullYear();
    const currentMonth = date.getMonth() + 1; // 👈️ months are 0-based
    const monthName = getMonthName(currentMonth)
    const currentDay = new Date().getDate();
    const daysInCurrentMonth = getDaysInMonth(currentYear, currentMonth);
    setYear(currentYear)
    setMonth(monthName)
    setDay(currentDay)
    setTotalDays(daysInCurrentMonth)
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Calendar Budget App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>year: {year} month: {month} day: {day}</p>
      <p>totalDays: {totalDays}</p>
    </div>
  )
}

export default Home
